### PR TITLE
bug: add missing Tokenserver headers

### LINKED ISSUE #1242: Fenix doesn't Sync with the syncstorage: Missing server timestamp header in request
I successfully managed to sync my bookmarks with Firefox for Desktop and my self-hosted syncstorage (with build in tokenserver).
But syncing with Fenix does not work.
The sync stops with error `sync failed: Missing server timestamp header in request`
Issue https://github.com/mozilla/application-services/issues/3379 describes similar symptoms.
This comment seems to be interesting:
> So this `sync failed: Missing server timestamp header in request` is very strange, and seems to indicate that you're getting a `200 OK` from tokenserver that somehow doesn't include the `X-Timestamp` header. This should *in theory* be impossible (which is one of the reasons we error on it) because there's a "tween" in the tokenserver server code that sets this header on every response. So, I'm not entirely sure what's happening here.
_Originally posted by @rfk in https://github.com/mozilla/application-services/issues/3379#issuecomment-667475080_

Maybe new tokenserver also doesn't include the `X-Timestamp` header?

Fenix settings:
custom account-server: empty/default
custom sync-server: https://mydomain.com/1.0/sync/1.5

ADB logcat:
```
03-06 08:27:23.250  5519  5561 I FirefoxAccount: Executing: get access token
03-06 08:27:23.280  5519  5561 I FirefoxAccount: Successfully executed: get access token
03-06 08:27:23.280  5519  5561 I FirefoxAccount: Executing: getTokenServerEndpointURL
03-06 08:27:23.281  5519  5561 I FirefoxAccount: Successfully executed: getTokenServerEndpointURL
03-06 08:27:23.286  5519  5561 I FxaDeviceConstellation: Refreshing device list...
03-06 08:27:23.286  5519  5561 I FxaDeviceConstellation: Executing: fetching all devices
03-06 08:27:23.374  5519  5560 I sync_manager::manager: No backoff in effect (or we decided to ignore it), starting sync
03-06 08:27:23.374  5519  5560 I sync15::sync_multiple: Syncing 6 engines
03-06 08:27:23.374  5519  5560 I sync15::sync_multiple: Loading/initializing persisted state
03-06 08:27:23.374  5519  5560 I sync15::sync_multiple: Preparing client info
03-06 08:27:23.374  5519  5560 I sync15::sync_multiple: Entering sync state machine
03-06 08:27:23.374  5519  5560 I sync15::sync_multiple: Advancing state machine to ready (full)
03-06 08:27:23.409  5519  5560 W sync15::sync_multiple: sync failed: Missing server timestamp header in request, final status=OtherError
03-06 08:27:23.409  5519  5560 W sync15::sync_multiple: Backtrace: None
03-06 08:27:23.409  5519  5560 I sync_manager::manager: Sync finished with status OtherError
03-06 08:27:23.411  5519  5560 E SyncWorker: 'Other' error :(
03-06 08:27:23.414  5519  5610 I WM-WorkerWrapper: Worker result FAILURE for Work [ id=6175d63b-5b6f-45d2-b55e-c18a77a3db25, tags={ Immediate, mozilla.components.service.fxa.sync.WorkManagerSyncWorker, Common } ]
03-06 08:27:24.505  5519  5561 I FxaDeviceConstellation: Successfully executed: fetching all devices
03-06 08:27:24.505  5519  5561 I FxaDeviceConstellation: Refreshed device list; saw 3 device(s).`
```
conf.toml
```
port=5000
database_url = "mysql://ffsync:passwd@localhost:3306/syncstorage_rs"
master_secret = "fd612d21680740d12bc4891994b55151662d204c"
human_logs = 1
disable_syncstorage = false
tokenserver.enabled = true
tokenserver.test_mode_enabled = false
tokenserver.node_type = "mysql"
tokenserver.database_url = "mysql://ffsync:passwd@localhost:3306/syncstorage_rs"
tokenserver.fxa_metrics_hash_secret = "fd612d21680740d12bc4891994b55151662d204c"
tokenserver.fxa_email_domain = "api.accounts.firefox.com"
tokenserver.fxa_oauth_server_url = "https://oauth.accounts.firefox.com"
cors_allowed_origin = "null"
cors_max_age = 86400
```

### PR DESCRIPTION
**Pull request by ethowitz**
## Description

Adds the missing `X-Timestamp` to responses from Tokenserver. The python equivalent can be found [here](https://github.com/mozilla-services/tokenserver/blob/master/tokenserver%2Ftweens.py#L13). I also double-checked the response from the Python Tokenserver to ensure there weren't any other missing headers that should be added here.

## Testing
I added new integration tests to check for the new headers.

## Issue(s)
Closes #1242

### CODE REVIEW

File: src/tokenserver/handlers.rs [hunk 1]
```diff
@@ -50,7 +50,15 @@ pub async fn get_tokenserver_result(
...
 
-    Ok(HttpResponse::build(StatusCode::OK).json(result))
+    let timestamp = {
+        let start = SystemTime::now();
+        start.duration_since(UNIX_EPOCH).unwrap().as_secs()
+    };
+    Ok(HttpResponse::build(StatusCode::OK)
+        .header("X-Content-Type-Options", "nosniff")
+        .header("X-Timestamp", timestamp.to_string())
+        .force_close()
```
Comment (ethowitz) [inline src/tokenserver/handlers.rs:60]: `syncstorage-rs` seems to optionally support keepalive based on the settings, so I'm not sure what the prod setting is. For now, Tokenserver will run as a separate server, and I've disabled keepalive for that server, but when we someday run Tokenserver as part of syncstorage, we may need to revisit whether we can keep setting `Connection: close` on Tokenserver responses if the server itself actually does support keepalive.

File: src/tokenserver/handlers.rs [hunk 2]
```diff
@@ -50,7 +50,15 @@ pub async fn get_tokenserver_result(
         node_type: req.node_type,
     };
 
-    Ok(HttpResponse::build(StatusCode::OK).json(result))
+    let timestamp = {
+        let start = SystemTime::now();
+        start.duration_since(UNIX_EPOCH).unwrap().as_secs()
+    };
+    Ok(HttpResponse::build(StatusCode::OK)
+        .header("X-Content-Type-Options", "nosniff")
```
Comment (ethowitz) [inline src/tokenserver/handlers.rs:58]: I wasn't sure how necessary this was, but it is found in responses from the Python Tokenserver, so I added it to be safe

Comment (pjenvey) [reply src/tokenserver/handlers.rs:58]: FYI:  It looks to be the Pyramid cornice library adding this header to the python tokenserver (I thought it was probably nginx)

File: src/tokenserver/handlers.rs (hunk 1 above)
Comment (pjenvey) [reply src/tokenserver/handlers.rs:60]: I'm seeing `Connection: keep-alive` from [tokenserver prod](https://token.services.mozilla.com/)

Comment (ethowitz) [reply src/tokenserver/handlers.rs:60]: Oh I didn't think to check the `/` endpoint on prod...I'll remove the `.force_close()` 👍🏻

File: src/tokenserver/handlers.rs (hunk 2 above)
Comment (ethowitz) [reply src/tokenserver/handlers.rs:58]: Do you think it would be helpful to keep? I just want to make sure omitting it doesn't change the behavior of clients if they've come to expect it

Comment (ethowitz) [reply src/tokenserver/handlers.rs:58]: Seems more the concern of nginx as opposed to the application code itself, so I'll remove it here and make a note to myself to include it there when we're ready

Comment (jrconlin) [reply src/tokenserver/handlers.rs]: ... Gonna be that person and say, "Please add a comment here to indicate that this field is expected by the client and that you're creating a rule in Nginx to specify it." 

Otherwise it may become tribal knowledge.

File: src/server/mod.rs [hunk 3]
```diff
@@ -312,6 +312,7 @@ impl Server {
         });
 
         let server = server
+            .keep_alive(None)
```
Comment (pjenvey) [inline src/server/mod.rs:315]: should probably kill this too after removing the `force_close`
