### PR TITLE
fix: implement batches on top of mysql

### LINKED ISSUE #51: Implement batch db calls
Solidify the batches table schema (base it off the python version's schema or can we use the go version's simpler design?) and implement its calls.

### PR DESCRIPTION
**Pull request by pjenvey**
like go-syncstorage, we just store the bsos' json in a text column,
concatenating batches together w/ newlines

also:

- fix load_collection_names handling of cache hits
- get_bsos limit handling after b066fba9
- kill the old schema files I forgot to remove

Closes #51, #18

### CODE REVIEW

File: src/db/mysql/batch.rs [hunk 1]
```diff
@@ -0,0 +1,272 @@
...
+
+pub fn create(db: &MysqlDb, params: params::CreateBatch) -> Result<results::CreateBatch> {
+    let user_id = params.user_id.legacy_id as i32;
+    let collection_id = db.get_collection_id(&params.collection)?;
+    let timestamp = db.timestamp().as_i64();
+    // Sync timestamps are in seconds and quantized to two decimal places, so
+    // when we convert one to a bigint in milliseconds, the final digit is
+    // always zero. But we want to use the lower digits of the batchid for
+    // sharding writes via (batchid % num_tables), and leaving it as zero would
+    // skew the sharding distribution.
```
Comment (rfk) [inline src/db/mysql/batch.rs]: Do you in fact do this sharding across multiple "batches" tables?

File: src/db/mysql/batch.rs [hunk 2]
```diff
@@ -0,0 +1,272 @@
...
+pub fn validate(db: &MysqlDb, params: params::ValidateBatch) -> Result<bool> {
+    let user_id = params.user_id.legacy_id as i32;
+    let collection_id = db.get_collection_id(&params.collection)?;
+    let exists = batches::table
+        .select(sql::<Integer>("1"))
+        .filter(batches::user_id.eq(&user_id))
+        .filter(batches::collection_id.eq(&collection_id))
+        .filter(batches::id.eq(&params.id))
+        .get_result::<i32>(&db.conn)
+        .optional()?;
```
Comment (rfk) [inline src/db/mysql/batch.rs]: This feels like it should also check whether the batch has expired.

File: src/db/mysql/batch.rs [hunk 3]
```diff
@@ -0,0 +1,272 @@
...
+    Ok(exists.is_some())
+}
+
+pub fn append(db: &MysqlDb, params: params::AppendToBatch) -> Result<()> {
+    // XXX: this is possibly an upsert
```
Comment (rfk) [inline src/db/mysql/batch.rs]: Not sure I agree about an upsert here, you should always know whether you have a new batch or an existing batch.

File: src/db/mysql/batch.rs [hunk 4]
```diff
@@ -0,0 +1,272 @@
...
+    let user_id = params.user_id.legacy_id as i32;
+    let collection_id = db.get_collection_id(&params.collection)?;
+    let bsos = bsos_to_batch_string(&params.bsos)?;
+    // XXX: also update expiry?
+    update(batches::table)
+        .filter(batches::user_id.eq(&user_id))
+        .filter(batches::collection_id.eq(&collection_id))
+        .filter(batches::id.eq(&params.id))
+        .set(batches::bsos.eq(batches::bsos.concat(&bsos)))
+        .execute(&db.conn)?;
```
Comment (rfk) [inline src/db/mysql/batch.rs]: If the batch has already expired, should this update it or return an error?  Also if the specified batch id does not exist, this should likely return an error rather updating zero rows.

File: src/db/mysql/batch.rs [hunk 5]
```diff
@@ -0,0 +1,272 @@
...
+    Ok(())
+}
+
+pub fn commit(db: &MysqlDb, params: params::CommitBatch) -> Result<results::CommitBatch> {
+    let bsos = batch_string_to_bsos(&params.batch.bsos)?;
+    db.post_bsos_sync(params::PostBsos {
+        user_id: params.user_id,
+        collection: params.collection,
+        bsos,
+    })
```
Comment (rfk) [inline src/db/mysql/batch.rs]: Ideally we should atomically delete the batch after commiting it, to ensure that it can't be committed twice.

File: src/db/mysql/batch.rs [hunk 6]
```diff
@@ -0,0 +1,272 @@
...
+
+        let bsos = vec![
+            postbso("b0", Some("payload 0"), Some(10), None),
+            postbso("b1", Some("payload 1"), Some(1000000000), None),
+        ];
+        append(&db, ab(uid, coll, id, bsos))?;
+
+        let batch = get(&db, gb(uid, coll, id))?.unwrap();
+        assert_ne!(batch.bsos, "".to_owned());
+        // XXX: expiry updated?
```
Comment (rfk) [inline src/db/mysql/batch.rs]: I don't have strong opinions about this, but my first instance is that expiry should not be updated.  Otherwise there's no finite bound on the ultimate lifetime of a batch, a misbehaving client could slow-drip add items to a batch and keep it alive indefinitely.

File: src/db/mysql/batch.rs [hunk 7]
```diff
@@ -0,0 +1,272 @@
...
+        .filter(batches::user_id.eq(&user_id))
+        .filter(batches::collection_id.eq(&collection_id))
+        .filter(batches::id.eq(&params.id))
+        .execute(&db.conn)?;
+    Ok(())
+}
+
+pub fn commit(db: &MysqlDb, params: params::CommitBatch) -> Result<results::CommitBatch> {
+    let bsos = batch_string_to_bsos(&params.batch.bsos)?;
+    db.post_bsos_sync(params::PostBsos {
```
Comment (rfk) [inline src/db/mysql/batch.rs]: Defering the work here to an existing `post_bsos_sync` method should give you a lot of edge-cases for free, such as proper handling of partial updates and ttl bumping.  I like it!  Handling those was a source of some complexity in the python code.

File: src/db/mysql/batch.rs (hunk 1 above)
Comment (pjenvey) [reply src/db/mysql/batch.rs]: Nope, so I removed this comment and the associated code

File: src/db/mysql/batch.rs (hunk 4 above)
Comment (pjenvey) [reply src/db/mysql/batch.rs]: Sounds good, I've added expiry checks here and other places

File: src/db/mysql/models.rs [hunk 8]
```diff
@@ -665,13 +670,31 @@ impl MysqlDb {
...
+    }
+
     pub fn timestamp(&self) -> SyncTimestamp {
         self.session.borrow().timestamp
     }
 
     #[cfg(test)]
-    pub(super) fn set_timestamp(&self, timestamp: i64) {
-        self.session.borrow_mut().timestamp = SyncTimestamp::from_i64(timestamp).unwrap();
+    pub(super) fn with_delta<T, E, F>(&self, delta: i64, f: F) -> std::result::Result<T, E>
```
Comment (rfk) [inline src/db/mysql/models.rs]: This is a neat little abstraction!
