### PR TITLE
fix: add the batch extractor + handler

### LINKED ISSUE #105: Port batch handler
Dependent on its extractor (#86)

### PR DESCRIPTION
**Pull request by pjenvey**
Closes #105, #86

and a cargo fmt in a separate commit

### CODE REVIEW

File: src/web/extractors.rs [hunk 1]
```diff
@@ -729,14 +753,113 @@ impl FromRequest<ServerState> for BsoQueryParams {
...
         })?;
         Ok(params)
     }
 }
 
+#[derive(Debug, Default, Clone, Deserialize, Validate)]
+#[serde(default)]
+pub struct BatchParams {
+    pub batch: Option<String>,
+    #[validate(custom = "validate_commit")]
```
Comment (bbangert) [inline src/web/extractors.rs]: Is this query or header params? I was including a bit in the validate function to indicate where they came from so the error would properly reflect the location. It'd be nice if the validate was capable of passing args as a partial so we could avoid funcs for each location.

File: src/web/extractors.rs [hunk 2]
```diff
@@ -869,6 +996,17 @@ fn validate_body_bso_ttl(ttl: u32) -> Result<(), ValidationError> {
     Ok(())
 }
 
+/// Verifies the batch commit field is valid
+fn validate_commit(commit: &String) -> Result<(), ValidationError> {
```
Comment (bbangert) [inline src/web/extractors.rs]: validate_qs_commit maybe

File: src/web/extractors.rs [hunk 3]
```diff
@@ -1314,6 +1453,66 @@ mod tests {
         assert_eq!(result.bsos.invalid.len(), 2);
     }
 
+    #[test]
+    fn test_valid_collection_batch_post_request() {
```
Comment (bbangert) [inline src/web/extractors.rs]: A test for invalid?
