### PR TITLE
fix: remove report_error from the transaction handler

### LINKED ISSUE #726: Remove report_error now that all transactions are handled within the handlers
As mentioned here https://github.com/mozilla-services/syncstorage-rs/pull/692#discussion_r452550425

### PR DESCRIPTION
**Pull request by pjenvey**
## Description
   
the sentry middleware will report these for it now
    
- adapt more tests to async for compatibility w/ grpcio 0.6
- expose a setting for Db pool's min_idle
    
## Testing

`cargo test` unit tests now pass

## Issue(s)

Closes #726, #727, #723
Issue #712

### CODE REVIEW

File: src/db/tests/db.rs [hunk 1]
```diff
@@ -403,9 +403,9 @@ async fn get_storage_timestamp() -> Result<()> {
     let db = test_db(pool.as_ref()).await?;
 
     let uid = *UID;
-    db.create_collection("col1".to_owned()).await?;
-    let col2 = db.create_collection("col2".to_owned()).await?;
-    db.create_collection("col3".to_owned()).await?;
+    db.create_collection("NewCollection1".to_owned()).await?;
```
Comment (jrconlin) [inline src/db/tests/db.rs:406]: 👍

File: src/server/test.rs [hunk 2]
```diff
@@ -225,50 +226,58 @@ where
...
-fn test_endpoint_with_body(method: http::Method, path: &str, body: serde_json::Value) -> Bytes {
+async fn test_endpoint_with_body(
+    method: http::Method,
+    path: &str,
+    body: serde_json::Value,
+) -> Bytes {
     let settings = get_test_settings();
     let limits = Arc::new(settings.limits.clone());
-    let app = test::init_service(build_app!(block_on(get_test_state(&settings)), limits));
+    let mut app = test::init_service(build_app!(block_on(get_test_state(&settings)), limits)).await;
```
Comment (Mcat12) [inline src/server/test.rs:236]: This line still contains a `block_on`

File: src/server/test.rs [hunk 3]
```diff
@@ -170,38 +170,39 @@ fn hkdf_expand_32(info: &[u8], salt: Option<&[u8]>, key: &[u8]) -> [u8; 32] {
...
 
-fn test_endpoint_with_response<T>(method: http::Method, path: &str, assertions: &dyn Fn(T) -> ())
+async fn test_endpoint_with_response<T>(method: http::Method, path: &str, assertions: &dyn Fn(T))
 where
     T: DeserializeOwned,
 {
     let settings = get_test_settings();
     let limits = Arc::new(settings.limits.clone());
-    let app = test::init_service(build_app!(block_on(get_test_state(&settings)), limits));
+    let mut app = test::init_service(build_app!(block_on(get_test_state(&settings)), limits)).await;
```
Comment (Mcat12) [inline src/server/test.rs:202]: This line still contains a `block_on`.
