### PR TITLE
fix: return a 415 for unsupported content-type headers

### LINKED ISSUE #76: Supported other statuses in ValidationErrorKind::FromDetails
Not all validation errors should be a 400, in this case we want a 415 Unsupported Media Type:

https://github.com/mozilla-services/syncstorage-rs/pull/75/files#diff-9de2327cbb67a90931e98ff70715da9dR205

### PR DESCRIPTION
**Pull request by philbooth**
Fixes #76, returning a 415 when the `Content-Type` header is wrong.

@pjenvey @bbangert r?

### CODE REVIEW

File: src/web/error.rs [hunk 1]
```diff
@@ -97,7 +98,21 @@ impl From<Context<HawkErrorKind>> for HawkError {
 
 impl From<Context<ValidationErrorKind>> for ValidationError {
     fn from(inner: Context<ValidationErrorKind>) -> Self {
-        Self { inner }
+        let status = match inner.get_context() {
+            ValidationErrorKind::FromDetails(ref _description, ref location, ref name) => {
+                if *location == RequestErrorLocation::Header
+                    && name.is_some()
+                    && name.as_ref().unwrap() == "Content-Type"
```
Comment (bbangert) [inline src/web/error.rs]: Can't you compare without the unwrap?
```rust
if *location == RequestErrorLocation::Header && name == Some("Content-Type") {
```

Comment (philbooth) [reply src/web/error.rs]: Ah, didn't know that, thanks.
